### ISSUE TITLE
tree is not automatically updated when a node is removed

### ISSUE THREAD

**Issue by pavlo-leheta** [ezraroi/ngJsTree#100]
Tree is not getting automatically updated when a node is removed by deleting that node element from the model array AFTER the tree was recreated by incrementing the version number in the tree config.

**Comment by pavlo-leheta** [comment]
I found a solution by incrementing a version in a tree config after removing a node element from the model array. This way it automatically updates.

**Comment by ezraroi** [comment]
This works without incrementing.... Please provadie a plunker
