### ISSUE TITLE
Can I use custom data format?

### ISSUE THREAD

**Issue by anatoly314** [ezraroi/ngJsTree#106]
As I understand from jsTree tutorial native plugin does support this feature. I just provide callback function which called on each node and I can format it as desired. Can I do same with `angularized` plugin?

For example my data node is following: 

```
       {
            "groupId": 21,
            "parentGroupId": 0,
            "groupName": "Network",
            "ownerId": "123456"
        }
```

So, instead of `id` I want to use `groupId`, instead of `parent` I want to use `parentGroupId` and instead of `text`  I want to use `groupName`.

Thank you in advance.

**Comment by ezraroi** [comment]
I am not aware of this plugin... just try :)

**Comment by smohammedyasin** [comment]
you can use core.data jsTree config. 

```
$('#your-tree').jstree({
    core : {
        data : function (node, cb) {
            $.ajax({ url : ... }).done(function (data) {
                cb([{ "id" : data.id, "text" : data.name }])
            });
        }, ...
```
similar question posted [here](http://stackoverflow.com/questions/30310474/jstree-with-custom-json-data)

**Comment by anatoly314** [comment]
@smohammedyasin , thank you. Will try it next time or perhaps it will be useful for someone else. I just make function which transform all my object accordingly to jsTree requirement every time when I need, works perfect.
