### ISSUE TITLE
not showing tree view

### ISSUE THREAD

**Issue by smohammedyasin** [ezraroi/ngJsTree#107]
Hello,

I'm not getting any tree view from treeData.
Please check http://plnkr.co/edit/3fv3RAA3VgBbVSd58OaT?p=preview.

did i missed anything?

Appreciate for quick response

**Comment by ezraroi** [comment]
Hi, you are missing the 'ngJsTree' in your module dependencies and also... you didn't include the library js file :)

**Comment by smohammedyasin** [comment]
Yes, Thank you.
