### ISSUE TITLE
support for angular 1.6.x

### ISSUE THREAD

**Issue by papakai** [ezraroi/ngJsTree#119]
we are interested in upgrading to latest angular 1.6.x release. package.json covers "angular": "~1.4"
Could you please investigate? Many thanks in advance!

**Comment by ezraroi** [comment]
can you please test and make a PR?

**Comment by papakai** [comment]
No sorry. We instead decided now to move away from your module and to use the original JS Tree instead. You may close this issue, as we do not longer require this.
