### ISSUE TITLE
Upgrade to AngularJS 1.6

### ISSUE THREAD

**Issue by rbatllet** [ezraroi/ngJsTree#124]
Is there any possibility to be compatible with angularJS 1.6?

currently, It's locked to AngularJS 1.5

**Comment by ezraroi** [comment]
can you test that this is working with 1.6?

**Comment by rbatllet** [comment]
Yes, It works with Angular 1.6.7 (last version).

I have not found any malfunction

**Comment by ezraroi** [comment]
done
