### ISSUE TITLE
scope.tree.jstree() undefined

### ISSUE THREAD

**Issue by liujoey** [ezraroi/ngJsTree#13]
I don't know if it's the problem of jstree 3.0.9, but when installed this directive, it shows `scope.tree.jstree('destroy')` undefined. But when I change it to `$(scope.tree).jstree('destroy')` it works.

So I think before you assign the `elm` to `scope.tree`, you need to wrap it with jQuery. So I modified your function a little bit:
```
scope.destroy = function () {
    var j_elm = $(elm);
    if (attrs.tree) {
        if (attrs.tree.indexOf('.') !== -1) {
            var split = attrs.tree.split('.');
            scope.tree = scope.$parent[split[0]][split[1]] = j_elm;
        }
        else {
            scope.tree = scope.$parent[attrs.tree] = j_elm;
        }

    } else {
        scope.tree = j_elm;
    }
    scope.tree.jstree('destroy');
};
```

**Comment by ezraroi** [comment]
It is working fine for me, no need to wrap it. Look on the demo code to understand how it is wokring

**Comment by ezraroi** [comment]
Validated with jstree 3.0.9, working fine. Create a plunker and I can try help you solve the problem

**Comment by liujoey** [comment]
ok, I found the problem. My bad, I load the javascript in a wrong sequence, the jQuery.js should be loaded before angular.js. I will remove this commit from the pull request.

**Comment by gaving** [comment]
@liujoey :+1:

Took ages trying to track down this issue!

**Comment by garciaba** [comment]
Same problem here, still can't figure out what's going wrong...

I'm loading the libraries in the following order and still getting the same error!

 ` <script src="bower_components/jquery/dist/jquery.min.js"></script>
    <script src="bower_components/angular/angular.min.js"></script>
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="bower_components/angular-ui-router/release/angular-ui-router.min.js"></script>
    <script src="bower_components/json3/lib/json3.min.js"></script>
    <script src="bower_components/oclazyload/dist/ocLazyLoad.min.js"></script>
    <script src="bower_components/angular-loading-bar/build/loading-bar.min.js"></script>
    <script src="bower_components/angular-bootstrap/ui-bootstrap-tpls.min.js"></script>
    <script src="bower_components/ng-js-tree/dist/ngJsTree.js"></script>
`

**Comment by ezraroi** [comment]
Post a plunker with the problem and i will try to help

**Comment by solovieff** [comment]
Still have the same problem (working with https://github.com/ezraroi/ngJsTree/issues/80#issuecomment-223734778)

**Comment by orizis** [comment]
Try to add this:
<link rel="stylesheet" href="bower_components/jstree/dist/themes/default/style.css" />

**Comment by pettanj** [comment]
We had the same issue using ES6 and webpack 4 and used imports-loader and expose-loader the following way to solve the jQuery issue in our webpack config:
```
module: {
  rules: [
    {
      test: require.resolve('angular'),
      use: 'imports-loader?$=jquery',
    },
    {
      test: require.resolve('jquery'),
      use: [
        {
          loader: 'expose-loader',
          options: 'jQuery',
        },
        {
          loader: 'expose-loader',
          options: '$',
        },
      ],
    },
  ]
}
```
ng-js-tree: 0.0.10
