### ISSUE TITLE
data binding not working for me

### ISSUE THREAD

**Issue by liujoey** [ezraroi/ngJsTree#14]
in the directive, when it first been initialized, it gets the data from outside model.
```
scope: {
                treeData: '=ngModel',
                shouldApply : '&'
            },
```
For instance I have assigned `home.treeData` to the directive, so `scope.treeData` also has the same data. Now if I change the value of `home.treeData`, it seem the `scope.treeData` was not updating, what am I doing wrong?

**Comment by ezraroi** [comment]
Hi,
check the demo code. If you still have questions, create a plunker and I will look on it
