### ISSUE TITLE
change made on jsTree, update back to model

### ISSUE THREAD

**Issue by liujoey** [ezraroi/ngJsTree#16]
not an issue, just a question. I added `contextmenu` plugin in the js-tree, so that I can right click a node and create a child. I've also added an event monitor `renameNode` so I can get the new node text and it's parent, then I updated this information back to treeData, but now the problem is the directive will detect this update, and automatically create a new node in the jsTree again with the same id and text.

Do you have any suggestion? The ideal way is when user change something on the tree, it update back to the model.

**Comment by windmaomao** [comment]
i guess, the question is that what if you don't want the model to be updated right away ?

if you are editing a piece of content, you do angular.clone to make sure you don't change the edited data.

so maybe you are right, the tree should update the model right away, and if you don't want this behavior, you do clone.

**Comment by ezraroi** [comment]
The idea is to add the new node to the nodes array, this will automatically update the tree. This is the Angular way to do it. Look on the demo, I am doing this, without the context menu but the same idea. I have implemented in other projects exactly the behavior you described
