### ISSUE TITLE
What is the data format

### ISSUE THREAD

**Issue by windmaomao** [ezraroi/ngJsTree#17]
i'm kinda of stuck here, and need some help in getting the tree displayed.

1) I did play with jstree first, and load the following data correctly. I know the only thing matters is the text and state, but I need the rest of data there for other purpose. 

    [
        {
            "created": "",
            "name": "/",
            "type": "directory",
            "size": 0,
            "children": [
                {
                    "created": "1422994495000",
                    "name": "homepage",
                    "type": "directory",
                    "size": 136,
                    "children": [
                        {
                            "created": "1422994489000",
                            "name": "carasole",
                            "type": "directory",
                            "size": 68,
                            "children": [],
                            "text": "carasole",
                            "state": {
                                "opened": true
                            }
                        }
                    ],
                    "text": "homepage",
                    "state": {
                        "opened": true
                    }
                },
                {
                    "created": "1422994495000",
                    "name": "others",
                    "type": "directory",
                    "size": 204,
                    "children": [
                        {
                            "created": "1422993066000",
                            "name": "bc",
                            "type": "directory",
                            "size": 68,
                            "children": [],
                            "text": "bc",
                            "state": {
                                "opened": true
                            }
                        }
                    ],
                    "text": "others",
                    "state": {
                        "opened": true
                    }
                }
            ],
            "text": "/",
            "state": {
                "opened": true
            }
        }
    ]

2) I used the following line

                    <div js-tree ng-model="treeData" tree-events="ready:treeReady;create_node:createNodeCB"></div>

and monitored the treeReady so that i know the tree is loaded

3) I know the treeData is there, because I can print it {{ treeData }}

4) however my tree is not displaying, so i wonder what i did wrong. Btw i didn't set any treeConfig. please help.

**Comment by windmaomao** [comment]
I checked the test, apparently this is the data format we used,

        scope.data = [
            { id : 'ajson1', parent : '#', text : 'Simple root node' },
            { id : 'ajson2', parent : '#', text : 'Root node 2' },
            { id : 'ajson3', parent : 'ajson2', text : 'Child 1' },
            { id : 'ajson4', parent : 'ajson2', text : 'Child 2' }
        ];

but i tried, it doesn't work either, so it might not be the data issue. I might not wire it correctly. 

the behavior is the widget will spin for 1 sec, and then disappears like it didn't get any data.

**Comment by ezraroi** [comment]
Hi
Please create a plunker and share it, i will look at it there

**Comment by windmaomao** [comment]
ok, i couldn't manage to get plunker running with angularJS, but i did download the demo, and plugged in my data, and it worked, so i know there's something I did wrong. 

one thing that i noticed is that you used (function(angular) { vs just

var app = angular.module("App");

**Comment by windmaomao** [comment]
ok, i finally get it working, the issue i had is the following.

    app.controller('FileListController', function ($scope, $state, File, $modal, $window, $http) {
        $scope.treeData = [
            { id : 'ajson1', parent : '#', text : 'Simple root node' },
            { id : 'ajson2', parent : '#', text : 'Root node 2' },
            { id : 'ajson3', parent : 'ajson2', text : 'Child 1' },
            { id : 'ajson4', parent : 'ajson2', text : 'Child 2' }
        ];
        $scope.treeConfig = {
            core: {
                multiple: false
            },
            version: 1
        }
        $scope.$on('$viewContentLoaded', function() {
            // get directories
            $http.get('http://localhost:1337').success(function(data) {
                $scope.treeData = [
                    { id : 'ajson1', parent : '#', text : 'Simple root node' },
                    { id : 'ajson2', parent : '#', text : 'Root node 2' },
                    { id : 'ajson3', parent : 'ajson2', text : 'Child 1' },
                    { id : 'ajson4', parent : 'ajson2', text : 'Child 2' }
                ];
                $scope.treeConfig.version++;
            })


ok, if i set $scope.treeData at the beginning, it's working, but if i put it under a $http, the tree doesn't appear.

Then i try played with should-apply, doesn't work, and eventually i realized the trick is on version ++ 

            $scope.treeConfig.version++;

I believe everything is mentioned in the Documentation on the front page.

**Comment by ezraroi** [comment]
Yes, if you change the treeData object you should change the version and this will recreate the tree (destroy the element and create it again).

**Comment by ezraroi** [comment]
By the way, you can achieve this without recreating the tree. Declare all the configuration in an object, and provide an empty array for the treeData. Once your $http request is finished, push all the data that you need to the treeData array and don't replace its reference. This will work for sure, as this is the right way to use it.

**Comment by windmaomao** [comment]
i see, that's right, that's how it works with jstree directly. I'll try it and let you know. 

FYI, currently, i don't declare a empty treeData initially, seems to me the tree only load once now after $http. Anyway, your approach might be most robust, since you never know what angularJS do before it reaches your http code.

**Comment by Rabi-Narayan** [comment]
H
[jsfile.txt](https://github.com/ezraroi/ngJsTree/files/103755/jsfile.txt)

i ezraroi,
modified in the way u suggested to make empty array and pushed the response data but it failed to create child nodes and gives error while trying to open a parent node.
treeCtrl: error from js tree - {"error":"nodata","plugin":"core","id":"core_05","reason":"Could not load node","data":"{\"id\":\"ajson1\"}"}


my config and data to load initial tree is like this.Given some initial data to populate tree because it is not creating any node in other ways.
vm.treeData = [
            { id : 'ajson1', parent : '#', text : 'Simple root node', state: { opened: false},children:true },
            { id : 'ajson2', parent : '#', text : 'Root node 2', state: { opened: false},children:true },
            ];
            
        
        vm.treeConfig = {
            core : {
                multiple : false,
                animation: true,
                error : function(error) {
                    $log.error('treeCtrl: error from js tree - ' + angular.toJson(error));
                },
                check_callback : true,
                worker : true
            },
            types : {
                default : {
                    icon : 'glyphicon glyphicon-flash'
                },
                star : {
                    icon : 'glyphicon glyphicon-star'
                },
                cloud : {
                    icon : 'glyphicon glyphicon-cloud'
                }
            },
            version : 1,
            plugins : ['types','checkbox']
        };



I am getting data from http service like this:

var promise = ravensService.getChildren();

I am calling the follwing function on "open_node" event of jsTree.But before this event i am getting above error :(
vm.openChildNode = function()
        {
            vm.treeData.push(data.data);
        };

        promise.then(function (data)
        {
        vm.treeData = data.data;
        console.log(vm.treeData);
        });


I have tried all the stuffs and working on same from days but unable to find solution.I am using jsTree in Angularjs.Since i am new to this please help in this regard.Thanks in advance.PFA for Js.
