### ISSUE TITLE
Will jsTree plugins get support?

### ISSUE THREAD

**Issue by neilakapete** [ezraroi/ngJsTree#2]
Is there any timeline for support of these available plugins?

**Comment by ericzon** [comment]
It could be interesting a simple example of the search plugin with ngJsTree.

Thx

**Comment by BhuvanaMani** [comment]
can someone help with ngJsTree demo with search plugin ?

**Comment by candidosales** [comment]
Search plugin don't work, anyone can help me?

**Comment by ezraroi** [comment]
I am using it in my projects, will add an example

**Comment by Sylvestre67** [comment]
Is there a working example with search that we can take a look at ?
