### ISSUE TITLE
does not work dnd-start / dnd-stop in dnd plugin

### ISSUE THREAD

**Issue by goodwilldd** [ezraroi/ngJsTree#20]
```
<div js-tree="treeConfig" should-apply="applyModelChanges()" ng-model="treeData" tree="treeInstance" tree-events="ready:readyCB;create_node:createCB;select_node:selectedNode;dnd_start:dndStart;dnd_stop:dndStop"></div>
```

```
$scope.dndStart = function() {
 console.log("11111");
}
```

it's not work!!

I know that that is fixed in the previous issue to understand.
However, no action is actually applied.
Am I doing wrong use?
I would like a guide to the Drag And Drop Event.

**Comment by ezraroi** [comment]
Did you enable the DND plugin in the jstree config?

**Comment by goodwilldd** [comment]
yes, my config 

```
					$scope.treeConfig = {
						core : {
							multiple : false,
							animation : true,
							error : function(error) {
								console.log('treeCtrl: error from js tree - '
										+ angular.toJson(error));
							},
							check_callback : true,
							worker : true
						},
						types : {
							"default" : {
								icon : 'fa fa-folder'
							},
							"Star" : {
								icon : 'fa fa-star'
							},
							"Cloud" : {
								icon : 'fa fa-cloud'
							}
						},
						version : 1,
						plugins : [ 'dnd', 'types' ]
					};
```

something wrong??

**Comment by ezraroi** [comment]
Please make a plunker with the problem and post here the link, I will take a look on it

**Comment by deezaster** [comment]
http://plnkr.co/edit/9ESl4GUg6Kj6rKzBnlmc?p=preview

please help/fix. thnx.

**Comment by ezraroi** [comment]
OK,
after checking the documentation of the JsTree again i saw the problem. the DND events are not triggered on the tree, but on the document itself. Check http://www.jstree.com/api/#/?f=dnd_start.vakata 

So you will need to register on the document by yourself for registering on the DND events

**Comment by deezaster** [comment]
here ab example for the documentation:

$(document).on('dnd_start.vakata', function (e, data) {
    console.log('Started');
});

**Comment by ezraroi** [comment]
Yes, you can see that the you need to register on the document, no need to register with the tree directive

**Comment by deezaster** [comment]
here an example to get the id's:

```javascript
   $(document).on('dnd_stop.vakata', function (e, data) {
      console.log('DND Stopped');

      var ref = $('.jstree').jstree(true);
      var id = ref.get_node(data.element).id;
      var parentId = ref.get_node(data.element).parent; // '#' = no parent!
      console.log("node :" + id + " attached to: " + parentId);
   }); 
```

**Comment by ezraroi** [comment]
thanks for sharing it

**Comment by meriturva** [comment]
HI! I have seen on version 0.0.4 dnd events: ['dnd_scroll','dnd_start','dnd_move','dnd_stop']
but i dont see any way to use them.....could you give us an example?
Thanks.

**Comment by ezraroi** [comment]
This was a try to catch the events, but the problem is that the plugin is not invoking them on the jstree instance but on the document. Check previous comments to see how to solve this issue

**Comment by meriturva** [comment]
Ok yes i have resolved using document events...so please delete the "dnd_xxx" reference on the js. So thanks.
