### ISSUE TITLE
Cannot asynchronously init ngJsTree

### ISSUE THREAD

**Issue by arcadeJHS** [ezraroi/ngJsTree#21]
Hi,
I cannot init the widget asynchronously loading data after an ajax call.
The tree stay empty.
Could you provide an example, please?

Pseucodode:
```
$scope.treeData = [];
function init(response) {
   $scope.treeData = response;
}
resource.get(null, init);
```

**Comment by ezraroi** [comment]
Create the options object with empty array. After thus, evey item you will add to the array will be added to the tree.

**Comment by arcadeJHS** [comment]
Well, it doesn't seem to work, actually.
The following code does not populate the tree:

```
<div js-tree ng-model="options"></div>
```
```
$scope.options = [];
$resource.get(init);
function init(response) {
    // $scope.options = response;
    $scope.options.push(response);
}
```

**Comment by arcadeJHS** [comment]
Finally I made it work, using the solution proposed on https://github.com/ezraroi/ngJsTree/issues/7:
incrementing by 1 the core.version property.

**Comment by ezraroi** [comment]
By incrementing the version you recreate the tree. I will update the demo to load the data async, i am using it in several projects in async way. You should increment the  the version only when you want to recreate the tree

**Comment by arcadeJHS** [comment]
Yes, and that way it works, thanx.
The only thing still I cannot understand is that jstree error in console:
```
Uncaught TypeError: Cannot read property 'triggerHandler' of null
```

**Comment by ezraroi** [comment]
If you write a plunker that reproduces this error message i will debug it. I never experienced such error before

**Comment by arcadeJHS** [comment]
I'll try to write a plunker as soon as I can.
By the way... it seems something in jstree code triggered by the nodesWatcher.onAdded.
Are you supposing a data structure where each item has a "parent" property?
I am actually using the "children" version of data definition:
```
{id: "1", text: "label", children: [...]}
```

**Comment by meriturva** [comment]
The same here: Uncaught TypeError: Cannot read property 'triggerHandler' of null when i call $scope.cpsStepsTreeConfig.version++; ...just without change the model

**Comment by arcadeJHS** [comment]
Yes, I found the problem relies exactly in that line of code: $scope.treeConfig.version++.
By the way I cannot replicate the erron on a plunker (http://plnkr.co/edit/4pvwj5rmKyMdYORJ9oY8?p=info). No error there. I cannot understand why.

By the way I found a viable solution by using ng-if on js-tree element. This eliminates the error.

    <div ng-if="treeData" js-tree="treeConfig" ng-model="treeModel"></div>

    $resource(URL).get().$promise.then(function(response) {
        $scope.treeData = response;
        // remaining ng-jstree initialization code
    });

**Comment by ezraroi** [comment]
The version++ hack is meant for recreating the tree from scratch.. you don't want to use if unless there is a real need for this

**Comment by arcadeJHS** [comment]
Well, in my situation I use it to redraw the tree after loading data through ajax.
Is there an alternative way?

**Comment by ezraroi** [comment]
The right way to load async data is to create the tree with an empty array of nodes. once your async data is returned from the server, push it to the array that you created the tree with. This way the binding will know of the change and will add the new nodes to the tree

**Comment by arcadeJHS** [comment]
I am not sure to get the point.
Could you please modify my plunker to show the right way?

**Comment by ezraroi** [comment]
I will try to find time to do it today, anyway. You can also you the resolve feature of angular and inject that data to the controller.

Will write once will look on the plunker

**Comment by arcadeJHS** [comment]
Thank you!

**Comment by pomarc** [comment]
hi! I get the same error when first loading the tree:
I do this
<pre>
 vm.treeData = [];
    angular.copy(myData, vm.treeData);
    vm.treeConfig = {
        core: {
            multiple: false,
            animation: true,
            error: function (error) {
                $log.error('treeCtrl: error from js tree - ' + angular.toJson(error));
            },
            check_callback: true,
            worker: true
        },
        types: {
            default: {
                icon: 'fa fa-file-code-o'
            },
            folder: {
                icon: 'fa fa-folder-o'
            },
            config: {
                icon: 'glyphicon glyphicon-settings'
            }
            ,
            solution: {
                icon: 'fa fa-cubes'
            }
            ,
            project: {
                icon: 'fa fa-cube'
            }
             ,
            settings: {
                icon: 'fa fa-cog'
            },
            file: {
                icon: 'fa fa-file-code-o'
            }
        },
        version: 1,
        plugins: ['types']
    };

    $scope.$apply();
</pre>

at the end I get the dreaded 
<pre>Uncaught TypeError: Cannot read property 'triggerHandler' of null</pre>

**Comment by brandonkboswell** [comment]
I also get this "Uncaught TypeError: Cannot read property 'triggerHandler' of null" error when initializing with an empty array of nodes and then changing it on $http.get

**Comment by cnicy** [comment]
$scope.treeData = null；
         <div ng-if="treeData != null">
                                <div id="jstree" js-tree="treeConfig" ng-model="treeData" tree="treeInstance" tree-events="changed:changedCB"></div>
                            </div>
