### ISSUE TITLE
Asynchronous loading nodes

### ISSUE THREAD

**Issue by Incognito-Nemo** [ezraroi/ngJsTree#22]
Hello!

When I load data1 all is ok but all the tree is loaded in one time.
data1 = [{
"id": 1, "parent": "#", "text": "Node 1", "children": [
{ "id": 2, "parent": "1", "text": "Node 2" },
{ "id": 3, "parent": "1", "text": "node 3" }
]
}];

I want use the loading tree nodes on expand node event.

So I use data2 and I have this error when I want to expand the first node: treeCtrl: error from js tree - {"error":"nodata","plugin":"core","id":"core_05","reason":"Could not load node","data":"{\"id\":\"1\"}"}   http://localhost:53001/Scripts/angular.js   Line 11655

data2 = [
  { "id": 1, "parent": "#", "text": "Node 1", "children": true },
  { "id": 2, "parent": "1", "text": "Node 2" },
  { "id": 3, "parent": "1", "text": "Node 3" }
];

How can I do it? It is a bug or a problem with my code?

**Comment by ezraroi** [comment]
Hi,
you can look on the demo page, I am loading async data there.
If this not solves your problem, please write a plunker that reproduces the problem and i will look on it

**Comment by Incognito-Nemo** [comment]
You can see the problem at http://plnkr.co/edit/DuG0LLvvqyNFBYVbi7Vh?p=preview

**Comment by ezraroi** [comment]
Looked on it, the problem is the 'children' : true property.
Remove it and everything is working fine

**Comment by Incognito-Nemo** [comment]
Yes I agree with you but if you don't set children to true, all the tree is loaded. 
I want to load node children after click on expand icon (because my tree is very big).

**Comment by ezraroi** [comment]
So why not init it as closed  and not open and register for the expend event of the node?

**Comment by Incognito-Nemo** [comment]
yes but how I register expand event?

**Comment by ezraroi** [comment]
http://www.jstree.com/api/#/?f=before_open.jstree

**Comment by Incognito-Nemo** [comment]
I modify Plunker on http://plnkr.co/edit/DuG0LLvvqyNFBYVbi7Vh?p=preview and it is not working… What I am missing?

**Comment by ezraroi** [comment]
I think you are using the jstree in a wrong way. You say it has children but the data you gave to the tree dosen't have children. It is not related to the nbJsTree directive

**Comment by ezraroi** [comment]
I think the tree is trying to open the node by default and it is not finding the data. You need to see how to prevent it form opening the node on selection

**Comment by Incognito-Nemo** [comment]
I can't get the before_tree event : I have the error treeCtrl: error from js tree - {"error":"nodata","plugin":"core","id":"core_05","reason":"Could not load node","data":"{\"id\":\"1\"}"}
https://rawgit.com/ezraroi/ngJsTree/master/demo/bower_components/angular/angular.min.js
Line 101 before… (http://plnkr.co/edit/DuG0LLvvqyNFBYVbi7Vh?p=preview)

Without Angular, I config Ajax jsTree with 'core' : {
  'data' : {
    'url' : function (node) {
      return node.id === '#' ? 
        'ajax_roots.json' : 
        'ajax_children.json';
    },
    'data' : function (node) {
      return { 'id' : node.id };
    }
  }

but with it seems to be impossible ?

Any idea to config your Angular with Ajax requests?

**Comment by Incognito-Nemo** [comment]
I found a solution : I load the grandchildren on before_open event.
Thanks for your help !
