### ISSUE TITLE
Tree Instance undefined after the tree is successfully created

### ISSUE THREAD

**Issue by cbalves** [ezraroi/ngJsTree#23]
Hi, I'm trying to create a directive for a Drag'n'drop tree using ngJsTree. The tree is created and works, but so far I've been unable to use the treeInstance, as it always shows up as "undefined".

I tried to adapt your solution from the https://github.com/ezraroi/ngJsTree/issues/8, and created a new plunker with a simple example of my code, which surprisingly works as expected:
http://plnkr.co/edit/onimKl8iGNyYUkRENW5T?p=preview

In my real application, the console.log for the TreeInstance keeps showing up as undefined, although the implementation is pretty similar. In this Plunker example, I'm not using a controller, but I have tried both approaches with the same unsuccessful result.

Any idea of what might be the problem?

Thanks in advance!

**Comment by ezraroi** [comment]
When do you print the TreeInstance to the console? 
if in the controller constructor it will not work, only after ready event of the tree is fired you can access it

**Comment by cbalves** [comment]
I print the treeInstance in the readyCB event, just like it's done in your previous plunker example: http://plnkr.co/edit/1PHjOqojZsVlQmP819PW?p=preview

I also created a button to print its value, like the one you have in your demo - "Call Method of Tree Instance" - but since the treeInstance is undefined, I get a "TypeError: Cannot read property 'jstree' of undefined"

**Comment by ezraroi** [comment]
If you can't reproduce this in plunker, it will be very hard to for me to help. The treeInsrance property is working fine in tests and in my projects

**Comment by Incognito-Nemo** [comment]
Same problem with jquery 2.1.3, angular 1.3.15, jsTree 3.1.0…

**Comment by ezraroi** [comment]
Did you manage to reproduce on plunker?

**Comment by cbalves** [comment]
Sorry for the late response. I was finally able to retrieve the treeInstance. In my case, the only solution was to use the ng-controller directive to define the controller (which I avoid using in my project):

<div ng-controller='myCtrl'>
    <div js-tree="treeConfig" ng-model="treeData" tree="treeInstance"></div>
</div>

I'm still unable to reproduce the working example of my first plunker or to get the treeInstance without having to use ng-controller.

Thanks a lot for your help and for this great Angular directive! Keep up the good work :)

**Comment by ModuloM** [comment]
Hi, 
I had the same issue and solved it by reference the instance in the controller by 
ctrl.treeInstance = angular.element('#myDivTreeElement') (just in case it helps)

Thanks for this very usefull work!

**Comment by ezraroi** [comment]
Happy to see that the directive is being used and thanks for sharing your solutions
