### ISSUE TITLE
check_all event 

### ISSUE THREAD

**Issue by nattynatty** [ezraroi/ngJsTree#25]
Hi,

In my form, I am trying to disable a button if no checkboxes are checked in a jstree component.
Whats the correct tree-event to be called? I have tried select_all/unselect_all as well but no luck. 

I am trying this:
js-tree="treeConfig" ng-model="treeData" should-apply="ignoreChanges" 
tree="treeInstance" tree-events="check_all:x();uncheck_all:y();"

$scope.y = function() {
	$scope.formDisabled = true;
};

But the scope variable is not updated on check_all or uncheck_all.

Any ideas would be appreciated.

Thanks

**Comment by nattynatty** [comment]
Here's how I am calling the directive:

<div js-tree="treeConfig" ng-model="treeData" should-apply="ignoreChanges" 
tree="treeInstance" tree-events="check_all:x();uncheck_all:y()"></div>

**Comment by ezraroi** [comment]
You have a syntax error, you are calling your method in the declaration. You should  write it this way:
<js-tree="treeConfig" ng-model="treeData" should-apply="ignoreChanges" 
tree="treeInstance" tree-events="check_all:x;uncheck_all:y;">

**Comment by nattynatty** [comment]
Thanks for your comment. I updated my syntax but it is still not triggered. Not sure why? The problem is with check_all and uncheck_all event. The other events : load_all, ready etc work fine.

**Comment by ezraroi** [comment]
I saw this in the JsTree docs:
triggered when all nodes are checked (only if tie_selection in checkbox settings is false).

Did you set the tie_selection to false in the tree configuration?

**Comment by nattynatty** [comment]
Yes, I have tried it with and without the tie_selection settings.

**Comment by ezraroi** [comment]
Can you please reproduce it on plunker so i will look on it?
