### ISSUE TITLE
check_node event

### ISSUE THREAD

**Issue by Incognito-Nemo** [ezraroi/ngJsTree#28]
Hello!

It seems that the check_node event is not fired : http://plnkr.co/edit/S1aJ1xtlEbfTfJRehmmE?p=preview

Where is the problem?

**Comment by ezraroi** [comment]
You are missing:
checkbox: {
              tie_selection: false
            },
in the tree config

check the jstree plugin docs

**Comment by hmendezm** [comment]
Hi ezraroi, I added checkbox: {
tie_selection: false
}, to the ngjstree but the check are gone.
I am prety sure I am doing wrong
 ` vm.treeConfig = {
            core : {
                multiple : false,
                animation: true,
                error : function(error) {
                    $log.error('treeCtrl: error from js tree - ' + angular.toJson(error));
                },
                check_callback : true,
                worker : true
            },
            version : 1,
            plugins : ['types','checkbox:{"tie_selection": false}']
        };
`
