### ISSUE TITLE
Respect state plugin

### ISSUE THREAD

**Issue by alexandernst** [ezraroi/ngJsTree#29]
I cloned the demo and tried adding objects to the `$scope.treeData` variable. The objects I was trying were added successfully, but I noticed that after refreshing the page the state of each node is not preserved/applied (open or closed).

I'm not sure if this is happening because I'm pushing the objects after the tree is instantiated (so when objects are pushed, state plugin has already kicked in and out and hasn't applied anything because there wasn't nodes in the tree) or because there is a bug in ngJsTree that doesn't respect the `state` plugin.

Can I get some help with this one, please?

**Comment by ezraroi** [comment]
Hi,
the jstree respects the `state` plugin. In my projects i am using the `state` plugin and also adding nodes after the tree is instantiated. If you can write a plunker with error it will be great. I will try to find time to add the `state` plugin to the demo and update it

**Comment by alexandernst** [comment]
Sorry for taking so long to reply.
Sure, check the bug here: http://plnkr.co/edit/1fjwJfPraHxGaYFB860b?p=preview

Note that I'm adding elements on the `ready` callback, with a `$timeout` (which simulates a custom service that I have, which does quite some operations with the retrieved data).

**Comment by alexandernst** [comment]
I think this is actually a jstree bug. State plugin kicks in right after the data is loaded (if any), so by the time I fill the `treeData` with actual values, state plugin has already applied the state (with no result) and then has cleared it.

Let's see what @vakata thinks about this one

**Comment by alexandernst** [comment]
@ezraroi So, after  talking with @vakata I think there is no easy solution.

I'll write here I fixed it for my code fi somebody gets here from a google search:

First, I store the state of the jstree onn page load, right before it gets wiped:

		state : {
			key : "asdasfasfasfasfasfasfqwefasfasf",
			filter: function(state) {
				$scope.tree_state = {};
				angular.copy(state, $scope.tree_state);
			}
		},

Then I subscribed to the `create_node` event:

	$scope.createNodeCB = function (e, item) {
		$scope.restoreState();
	};

And then I added this function:

	$scope.restoreState = _.debounce(_.once(function() {
		$scope.treeInstance.jstree(true).set_state($scope.tree_state);
	}), 100);

That will create a function that will run get executed only once, 100ms after the last call that was made to it. It uses underscore, so you'll have to add that.

**Comment by ezraroi** [comment]
Thanks for sharing this @alexandernst
