### ISSUE TITLE
When ngJsTree has multiple root nodes, only one root node is selectable

### ISSUE THREAD

**Issue by khendys** [ezraroi/ngJsTree#30]
First of all, great implementation!

When I add multiple root nodes, each with multiple children to ngJsTree I am unable to select both root nodes at the same time.  I am also unable to select individual children of those root nodes.  In summary, the tree just starts producing weird behavior.

To reproduce:
1. Go to your demo page
2. Add 2 child nodes to "Simple root node" (e.g. Child 3 and Child 4)
3. Try to select both Child 4 and the previously existing Child 2 (child of Root node 2)
![screen shot 2015-05-08 at 6 22 30 pm](https://cloud.githubusercontent.com/assets/8827476/7546815/479137c2-f5b0-11e4-8a38-92bd46e982f2.png)

Works in Original jsTree:
![screen shot 2015-05-08 at 6 20 48 pm](https://cloud.githubusercontent.com/assets/8827476/7546827/5b913e0c-f5b0-11e4-8895-01624a7b1574.png)

**Comment by khendys** [comment]
After perusing the code, it seems you are simply mapping/linking the tree events and properties between angular and jsTree.  I dug a little further and found that your demo app (and subsequently my app) had the jsTree core.multiple property set to false, which seems to have been intended to prevent multiple nodes from being selected (http://www.jstree.com/api/#/?q=core&f=$.jstree.defaults.core.multiple).  However, I don't think that's working as designed.

The issue is with base jsTree implementation, not with ngJsTree.  Closing the issue.

**Comment by ezraroi** [comment]
thanks for checking this
