### ISSUE TITLE
TypeError: scope.tree.jstree(...).set_type is not a function

### ISSUE THREAD

**Issue by alexandernst** [ezraroi/ngJsTree#31]
Everytime I finish renaming an item, I get this:

    TypeError: scope.tree.jstree(...).set_type is not a function
        at Object.link.nodesWatcher.onChanged (ngJsTree.js?v=1431071680:164)
        at changeWatcher.applyChanges (ngJsTree.js?v=1431071680:63)
        at Object.fn (ngJsTree.js?v=1431071680:81)
        at Scope.$get.Scope.$digest (angular.js?v=1431000285:14308)
        at angular.js?v=1431000285:14505
        at completeOutstandingRequest (angular.js?v=1431000285:4924)
        at angular.js?v=1431000285:5312

**Comment by ezraroi** [comment]
Can you please write a plunker that reproduces it?
The right way to rename an item is updating the item in your nodes array, the directive will rename it in the tree for you. This is the angular way

**Comment by alexandernst** [comment]
Hmmm... weird. I tried to reproduce the bug ([here](http://plnkr.co/edit/vYCMFPX7PDMkwV8gHLAx?p=preview)), but no luck. Anyways, keep in mind that modifying the data from Angular, while being the angular way, is not the optimal way. jstree already offers a method that will create an edit box on top of a node and handle the input. Why would I want to  re-implement such a functionality just to modify the array of data and make angular modify jstree's nodes?

Back to my issue. The error seems to happen when I change the text of one node inside angular's data . I was able to workaround the bug by make ng-js-tree ignore the changes made to angular's data and then restoring back the original behaviour using the `should-apply()` element from the directive.

I'm closing this until I can reproduce the error again.

**Comment by alexandernst** [comment]
@ezraroi Actually, I gave this a second though. Angular offers two-way bindings, so modifying the DOM (the text of each node) should be reflected in Angular's data (and viceversa). You should implement that, imho.

**Comment by ezraroi** [comment]
Will try to find time to see if I can implement this. For your bug, if you can reproduce it please notify me. In my projects i am updating the nodes all the time with no problems

**Comment by ezraroi** [comment]
After thinking about it a little bit more, I am afraid that I will not be able to implement it the way you asked. You have 2 way biniding in the current implementation. You just have to work with the data you supply to the directive and not by updating the nodes by the jstree api. If you will bind the name of the nodes in your nodes array to UI element and update it from the UI, it will be updated in the jstree. But also tracking changes made directly on the tree itself will be endless loop and can not be resolved

**Comment by ezraroi** [comment]
A workaround to make this work, you can give the node edit function a callback that what it is doing is updating your set of data with the new text, and this will make sure the tree will be updated also with the data (it will re assign the same name to the node, but will keep your data synced with the tree data). You may need to make the changes in the callback in inside $apply so angular will know about your changes

**Comment by alexandernst** [comment]
Indeed, I see the problem. Also, that is exactly how I was doing it :) (see my plunkr). Ok, closing this.
