### ISSUE TITLE
checkbox check_all() issue

### ISSUE THREAD

**Issue by teo89** [ezraroi/ngJsTree#34]
I am using checkbox plugin. I make a call of check_all() like that

$scope.treeReady = (e, data) ->
            $scope.treeInstance.jstree(true).check_all()

Everything looks fine but in browser console i get that error:
TypeError: $scope.treeInstance.jstree(...).check_all is not a function

I am using ngJsTree and jstree version 3.0.8

Thank you.

**Comment by ezraroi** [comment]
Please write a plunkr that reproduces the issue

**Comment by teo89** [comment]
Sorry it was invalid at the end. I solve it, it was a data issue
thanks and sorry again.
