### ISSUE TITLE
New Node added no show

### ISSUE THREAD

**Issue by jmelosegui** [ezraroi/ngJsTree#35]
Hi @ezraroi,

Thanks for creating and sharing this project.

I am trying to add a new node using a custom context menu. 
After the new node is added I can see it inside the treeData array, but it doesn't show on the tree though.

I have created a [plunker](http://plnkr.co/edit/CqkvnW) reproducing this issue.

I appreciate any help.

**Comment by ezraroi** [comment]
you will need to use $timeout as the adding to the vm.treeData is executed outside if angular as this is an javascript executed by the jstree component it self.

```javascript
$timeout(function() {
  vm.addValue($node);
});
```

**Comment by jmelosegui** [comment]
Thanks for the fast response. It works !!!!!
