### ISSUE TITLE
set_type is not a funciton

### ISSUE THREAD

**Issue by alexandernst** [ezraroi/ngJsTree#37]
The function `nodesWatcher.onChanged` tries to call `set_type`, which is not a jstree core function, but a function added by the `types` plugin (which is not required to run jstree itself).

This is breaking my code because it's trying to call a method that doesn't exist.

I suggest checking if `set_type` exists before trying to call it.

**Comment by ezraroi** [comment]
Can you please write a plunker that reproduces this issue?

**Comment by alexandernst** [comment]
@ezraroi Here you go http://plnkr.co/edit/uujSp4HVrwYYxgZEXOQa?p=preview

When you open the demo, after 4sec the text of the first element will be changed. However, if you remove "`types`" plugin, it will crash, because of the bug I described.

**Comment by Abhi-joshi** [comment]
We'll need a fast searching because there are about 4500 nodes in total.. And i saw that jstree solves that problem https://github.com/vakata/jstree/commit/56bdb98d2fdc4fa8ea8fff8acfbd85c9073a2472
Can you please provide a workaround for that in angular

**Comment by ezraroi** [comment]
@Abhi-joshi how is this connected to this issue?

**Comment by Abhi-joshi** [comment]
I'm new in Git and don't know how to create or contribute. Sorry for that.Can you help me out in this issue for searching.

**Comment by ezraroi** [comment]
This is using the js-tree... just search the tree with the js-tree api or just search your array of nodes that is binded to the tree

**Comment by Abhi-joshi** [comment]
How to accomplish this in your api's??

**Comment by Abhi-joshi** [comment]
Any luck in this because i'm using your api's for tree..

**Comment by alexandernst** [comment]
@Abhi-joshi this library is just a wrapper on top of jstree. As @ezraroi said, use jstree's API to search your data.

**Comment by Abhi-joshi** [comment]
@alexandernst so which api's should i use for it?? one of them is  search api i guess..

**Comment by ezraroi** [comment]
read the jstree docs and like I worte before, you can search your array of nodes and select the relevant node using the jstree api
