### ISSUE TITLE
why tree-events always use $timeout ?

### ISSUE THREAD

**Issue by beautifulinda** [ezraroi/ngJsTree#39]
[demo](http://ezraroi.github.io/ngJsTree/) html:

    <div js-tree="vm.treeConfig" should-apply="vm.applyModelChanges()" ng-model="vm.treeData" tree="vm.treeInstance" 
	tree-events="ready:vm.readyCB;create_node:vm.createCB"></div>

related event handler

    vm.readyCB = function() {
        $timeout(function() {
            vm.ignoreChanges = false;
            toaster.pop('success', 'JS Tree Ready', 'Js Tree issued the ready event')
        });
    };

    this.createCB  = function(e,item) {
        $timeout(function() {toaster.pop('success', 'Node Added', 'Added new node with the text ' + item.node.text)});
    };

my question is why all these **tree-events** have to use **$timeout** ?
Please kindly tell me, thank you!

**Comment by ezraroi** [comment]
This is they are JavaScript events issued by the tree, so Angular is not aware of them
