### ISSUE TITLE
How close all nodes programmatically, when several nodes is opened? 

### ISSUE THREAD

**Issue by DanStopka1985** [ezraroi/ngJsTree#41]
Hello! I using ngJsTree, it's a super helpful for me! But i don't know, how close  all nodes programmatically, when several nodes is selected. How can i do this? Thanks!

**Comment by ezraroi** [comment]
Did you check the js tree docs? 
https://www.jstree.com/api/#/?f=close_all([obj, animation])

You can use the api of the tree for that

**Comment by DanStopka1985** [comment]
I'am tried this: $scope.treeInstance.jstree(true).close_all(); 
but nothing happened.
I posted my question there http://stackoverflow.com/questions/32911978/how-collapse-all-ng-js-tree-nodes-programmatically

**Comment by ezraroi** [comment]
Answered your question, closing the issue as this is not an issue of the ngJsTree
