### ISSUE TITLE
ngJsTree into accordion bootstrap

### ISSUE THREAD

**Issue by DanStopka1985** [ezraroi/ngJsTree#43]
I using ngJsTree into 
&lt;accordion&gt;
    &lt;accordion-group>
        &lt;accordion-heading>
        &lt;/accordion-heading>
    &lt;div js-tree="treeConfig" should-apply="true" ng-model="treeData" tree="treeInstance" tree-events="ready:readyCB">&lt;/div>
    &lt;/accordion-group>
&lt;accordion>

and have $scope.treeInstance === undefined
out of this tags $scope.treeInstance !== undefined

How can i use accordion and ngJsTree toogether? Thanks!

**Comment by ezraroi** [comment]
Please write a plunker that reproduce this issue

**Comment by DanStopka1985** [comment]
http://plnkr.co/edit/k7awzQrMdUgAHqNfErSe?p=preview

**Comment by ezraroi** [comment]
You have some problems with scopes and controllerAs syntax.

Look on the fixed version: http://plnkr.co/edit/OtUQBUFjmyPsNhnG21zd?p=preview

**Comment by DanStopka1985** [comment]
Thank you!
