### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by ahmadigbaryia** [ezraroi/ngJsTree#44]
Hi,

I couldn't get the context menu running, here is my configurations:

$scope.i_treeConfig = {
...
                            contextmenu: {
                                items: function(node, callback){
                                    var rename = {
                                            label: "Rename",
                                            action: function(node){
                                                $scope.i_treeInstance.edit(node);
                                            },
                                            shortcut: '113',
                                            shortcut_label: "F2"
                                        };
                                    var actions = {rename: rename};
                                    callback(actions);
                                    return actions;
                                }
                            },
...
                            plugins: ["wholerow", "dnd", "types", "contextmenu"]
                        };

... 
some where in the HTML

<div tree="i_treeInstance" js-tree="i_treeConfig" ng-model="i_treeModel" should-apply="true" tree-events="copy_node: copyNodeCB;move_node: moveNodeCB;select_node:selectNodeCB"></div>

the contextmenu won't appear, have i miss something?

Thanks
Ahmad

**Comment by ezraroi** [comment]
The context menu plugin is working fine. Please write a plunker that reproduces your problem and I will try to fix it.

**Comment by ezraroi** [comment]
@ahmadigbaryia any updates?

**Comment by DanStopka1985** [comment]
http://plnkr.co/edit/noaPgzEKjjSWueciCTgQ?p=preview
it works!
