### ISSUE TITLE
Updating Angular and JsTree version

### ISSUE THREAD

**Issue by VigneswaranMarimuthu** [ezraroi/ngJsTree#45]
Hey,

First of all, Thanks for the angular directive for JsTree :+1: 

Do you have plans of updating Angular and JsTree versions (in your bower.json) ?

**My CI builders are failing due to version mismatch.**

**P.S:** I am currently using this directive with latest versions of Angular and JsTree. Everything seems to be working fine.

**Comment by ezraroi** [comment]
Done
