### ISSUE TITLE
can i select node, but not check/uncheck it?

### ISSUE THREAD

**Issue by DanStopka1985** [ezraroi/ngJsTree#48]

**Comment by ezraroi** [comment]
@DanStopka1985 Please check the jsTree documentation for this. Sounds like it can be done

**Comment by DanStopka1985** [comment]
I could not find this in docs, http://stackoverflow.com/questions/33690452/can-i-select-a-node-but-not-check-uncheck-it-in-jstree Can you help me?

**Comment by DanStopka1985** [comment]
checkbox : {
    tie_selection : false,
    whole_node : false
}
it works as i need.
Thanks!

**Comment by ezraroi** [comment]
Thanks for sharing
