### ISSUE TITLE
context menu in ngJsTree not work in modal

### ISSUE THREAD

**Issue by DanStopka1985** [ezraroi/ngJsTree#50]
http://plnkr.co/edit/1CgO3K9Y9R2tPkWplkFY?p=preview
modal opening on click on button "modal".

**Comment by ezraroi** [comment]
looks like a bug in the js tree itself. try to reproduce it without the directive, by using the js tree directly. Pretty sure it dosen't come for the directive

**Comment by DanStopka1985** [comment]
i reproduced this for jsTree http://stackoverflow.com/questions/33753321/contextmenu-plugin-not-work-bug-in-jstree

**Comment by ezraroi** [comment]
Please open issue on the jsTree repository

**Comment by DanStopka1985** [comment]
https://github.com/vakata/jstree/issues/1281

**Comment by ezraroi** [comment]
thanks
