### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by swamim** [ezraroi/ngJsTree#55]
Uncaught RangeError: Maximum call stack size exceeded
parse_flat @ (program):19parse_flat @ (program):84

I am loading a 400 node array. Please help.

**Comment by ezraroi** [comment]
I think this is the same issue as #54. Can you reproduce it please? In my project I am loading 2000 when I create the tree

**Comment by swamim** [comment]
Found issue, got the object which is having id and parent are the same, that is causing the issue. In this case, I have changed the object parent = "#" where ever id and parents are same. Tree is working fine.

**Comment by ezraroi** [comment]
Thanks for updating
