### ISSUE TITLE
Please write an example where by modifying the raw data JSON the tree gets dynamically updated

### ISSUE THREAD

**Issue by PedroD** [ezraroi/ngJsTree#56]
I am aware that by reloading the tree this can be done, but that is not the way binding is expected to work, since current opened nodes, selected nodes, etc are all lost due to the reloading operation.

I would like to be able to have a two way binding between the three and the raw json showed in this demo: https://ezraroi.github.io/ngJsTree/

is that possible? Thanks!

**Comment by ezraroi** [comment]
Just look on the demo source code in the repository

**Comment by renandegrandi** [comment]
There is an attribute (should-apply), it must be assigned as (true), so any change in the object tree, will be applied.
