### ISSUE TITLE
tree refresh problem from a second ng-controller

### ISSUE THREAD

**Issue by developerdu** [ezraroi/ngJsTree#59]
I've come across a problem where the tree does not reflect any updates if the change was made under a separate instance of an ng-controller like below.  So if the "add node" button is included under the first ng-controller, everything works as expected.  If it is included as in the code below, the addNode() method gets invoked however the tree does not show any new nodes.

I've got this situation because my "add node" button is in my editor which is separate to my tree.  JsTree itself does not have a problem with this situation - only ngJsTree.

        <div ng-controller="MainController as vm">
            <div js-tree="vm.treeConfig" should-apply="vm.applyModelChanges()" ng-model="vm.treeData" tree="vm.treeInstance" tree-events="changed:vm.changedCB"></div>
        
        </div>
        
        <div ng-controller="MainController as vm">
            <button ng-click="vm.addNode()">Add Node</button>
        </div>

**Comment by ezraroi** [comment]
Can you please reproduce it on plunker? 

Make sure you use the same array in both controllers
