### ISSUE TITLE
Search plugin example

### ISSUE THREAD

**Issue by EBS-EladRubin** [ezraroi/ngJsTree#60]
Hi, 

Thanks for this amazing Directive. Can we have a working example for search plugin?

Thanks!

**Comment by ezraroi** [comment]
Hi @EBS-EladRubin ,
I hope I will have some time this week or next week to try and write an example.

**Comment by EBS-EladRubin** [comment]
Hi thanks for the response, here is a working example:
Under tree controller:
    //------------------------------------------------------------------------------------------------------------------//
    vm.applySearch = function (){
      var to = false;
      if(to) {
        clearTimeout(to);
      }
      to = setTimeout(function () {
        if(vm.treeInstance) {
          vm.treeInstance.jstree(true).search($scope.elementsTreeSearch);
        }
      }, 250);
    };
    //------------------------------------------------------------------------------------------------------------------//
Under Html:
<input type="text" ng-model="elementsTreeSearch" ng-keyup="vm.applySearch()" class="ng-tree-search form-control tree-machines-search" placeholder="Search Machine" ng-keyup="vm.treeInstance.jstree(true).search('Machines')">

**Comment by EBS-EladRubin** [comment]
Under Html:
<input type="text" ng-model="elementsTreeSearch" ng-keyup="vm.applySearch()" class="ng-tree-search form-control tree-machines-search" placeholder="Search Machine" ng-keyup="vm.treeInstance.jstree(true).search('Machines')">
<input type="text" ng-model="elementsTreeSearch" ng-keyup="vm.applySearch()" class="ng-tree-search form-control tree-machines-search" placeholder="Search Machine" ng-keyup="vm.treeInstance.jstree(true).search('Machines')">

**Comment by EBS-EladRubin** [comment]
Under Html:
//------------------------------------------------------------------------------------------------------------------//
<input type="text" ng-model="elementsTreeSearch" ng-keyup="vm.applySearch()" class="ng-tree-search form-control tree-machines-search" placeholder="Search Machine" ng-keyup="vm.treeInstance.jstree(true).search('Machines')">
<input type="text" ng-model="elementsTreeSearch" ng-keyup="vm.applySearch()" class="ng-tree-search form-control tree-machines-search" placeholder="Search Machine" ng-keyup="vm.treeInstance.jstree(true).search('Machines')">
//------------------------------------------------------------------------------------------------------------------//

**Comment by ezraroi** [comment]
Thanks!

**Comment by morteza-gho** [comment]
**HTML**

`<input type="text" ng-model="search" ng-keyup="applySearch(search)" placeholder="search">`

**JS**

```
$scope.applySearch = function (){
            var to = false;
            if(to) {
               clearTimeout(to);
            }
            to = setTimeout(function () {
               if($scope.treeInstance) {
                  $scope.treeInstance.jstree(true).search($scope.search);
               }
            }, 250);
         };
```
