### ISSUE TITLE
Pass Events as Object to decrease clutter

### ISSUE THREAD

**Issue by PD75** [ezraroi/ngJsTree#62]
Hi,

The "tree-events" got cluttered so I decided to add the ability to pass an object with the events, in my case:
ctrl:    vm.treeEvents = {
      "ready": readyCB,
      "activate_node": activateNodeCB,
      "open_node": openNodeCB,
      "close_node": closeNodeCB,
    };
html: tree-events-obj="vm.treeEvents"

Is this somethings that you would like to include in your code?

Best Regards

Paul
PS. I am newbie on GitHub...... DS.

**Comment by ezraroi** [comment]
Hi @PD75 ,
thanks for the suggestion. 

You can create a Pull Request and i will check it. If everything will look fine i will add it

**Comment by PD75** [comment]
I think I got it, let me know otherwise.

/Paul

**Comment by ezraroi** [comment]
Thanks for the contribution
