### ISSUE TITLE
Wrong version of library is in NPM

### ISSUE THREAD

**Issue by icfantv** [ezraroi/ngJsTree#67]
Just a head's up that the wrong version of your library is being served up by NPM.  Since you don't use version numbers in your JS, I can't be certain what version it _is_ serving up, but it's definitely older than when you added the `tree-events-obj` attribute because that's missing from the NPM version.

**Comment by ezraroi** [comment]
it was the 0.0.7 version. Published 0.0.8

**Comment by icfantv** [comment]
Cool, thanks!
