### ISSUE TITLE
ngJsTree into tabs bootstrap

### ISSUE THREAD

**Issue by CicciMTS** [ezraroi/ngJsTree#69]
Hi, when i put ngJsTree into a tab of bootstrap the tree is loaded, but on select of node I have an error console: Uncaught TypeError: Cannot read property 'jstree' of undefined.

**Comment by CicciMTS** [comment]
Solved with this Issue https://github.com/ezraroi/ngJsTree/issues/23 ;)

**Comment by ezraroi** [comment]
Thanks
