### ISSUE TITLE
Using AngularJs ng-repeat to create Html Template

### ISSUE THREAD

**Issue by poonsv** [ezraroi/ngJsTree#73]
I usually create an Html Template using ng-repeat for a list of data and 2-way binding using $scope.treeData.
I tried to use ngJsTree and put put the ng-repeat inside div tag of jstree, but nothing shows up. I checked the generated Html, anything inside the div tag does not being generated.
Any idea how to use jstree in Angular way.

```
<div js-tree="vm.treeConfig">
       <ul>
            <li data-jstree='{"opened":true}' ng-repeat="node in vm.treeData" ng-include="'Web/Plans/testPlanTreeNodes.html'">
              </li>
        </ul>
 </div>
```

**Comment by ezraroi** [comment]
The js tree directive is painting the nodes.. no need for the ng-repeat.
You can not write anything inside the jsTree element.

Look on the demo code
