### ISSUE TITLE
treeInstance is not populated

### ISSUE THREAD

**Issue by aroder** [ezraroi/ngJsTree#74]
It looks like the directive's scope attribute does not include a tree attribute. The calling controller's property that should point to an instance of jsTree is instead null, even in the ready callback.

The test to test that this item is populated do pass, so maybe I am missing something.

**Comment by ezraroi** [comment]
It is working... you can check the demo code also.. probably some scopes problem you have in your code.

**Comment by aroder** [comment]
I checked it with the demo code; you are right, it is populated. Probably has to do with scopes. I will close this because the other issue also has to do with scopes #75

**Comment by aroder** [comment]
I'm developing in TypeScript. In the compiled javascript, the "this" context for the jsTree callback events is the jsTree dom element. I'm diggin in now to see what I can understand about the compiled javascript that is causing this.
