### ISSUE TITLE
Updating dependencies

### ISSUE THREAD

**Issue by VigneswaranMarimuthu** [ezraroi/ngJsTree#76]
Hi,

Can you update angular dependency ? I am using latest angular code base and since this plugin uses 1.4, my Jenkins builds are failing.

**Comment by ezraroi** [comment]
Need to test if working with Angular 1.5.
You probably can fix this in your build, doesn't make sense that your build will fail in 3th party libraries dependencies

**Comment by VigneswaranMarimuthu** [comment]
I am using this plugin with Angular 1.5 and it is working. You can update the dependency once tested. The build is failing due to plugin incompatibility when running **bower install** command. I think i should downgrade Angular to 1.4 to make the build to pass.

**Comment by VigneswaranMarimuthu** [comment]
@ezraroi I am using this library with Angular 1.5.8 for about 4 months and it is working. Haven't faced any issues yet. Can you test it once and update the dependency ?

**Comment by ezraroi** [comment]
Will do so

**Comment by ezraroi** [comment]
done
