### ISSUE TITLE
Node click event

### ISSUE THREAD

**Issue by JasonCSharpCoder** [ezraroi/ngJsTree#82]
how to config or code a click event function for the tree node?
thks!

**Comment by charon4ever** [comment]
I have the same question.How to add a click event on the node of the tree?

**Comment by ezraroi** [comment]
you have the event of the js tree.
Please check the js tree docs:
https://www.jstree.com/api/#/

**Comment by migarc1** [comment]
As ezraroi mention, first, you need to check the events list. Then, you have to put it in as follows:

In the HTML file:
`< js-tree="treeConfig" tree-events="select_node:selectNode;open_node:openNode" />`

In the Controller:
`
$scope.selectNode = function(node, selected, event){
 console.log(selected);
}

$scope.openNode = function(node){
}`
