### ISSUE TITLE
angular js , ng-model not ready 

### ISSUE THREAD

**Issue by justinhomes** [ezraroi/ngJsTree#95]
I am using https://github.com/ezraroi/ngJsTree and I have come across the following problem.

My ng-model is a AJAX request and when my controller fires, data is not yet ready, so it does not render anything.

    <div ng-controller='myCtrl'>
        <div js-tree="treeConfig" ng-model="treeData" should-apply="ignoreModelChanges()" tree="treeInstance" tree-events="ready:readyCB;create_node:createNodeCB"></div>
    </div>

https://plnkr.co/edit/fCrupsxDMprHdLCocZIe?p=preview

**Comment by ezraroi** [comment]
you are missing`ng-app="plunker"` and also check the browser console, your application is not working.. Angular is not loaded

**Comment by justinhomes** [comment]
i have fixed the plunker for the problem still exists.

**Comment by ezraroi** [comment]
you are missing treeConfig
