### ISSUE TITLE
NgJsTree Modal updates not picked up 

### ISSUE THREAD

**Issue by justinhomes** [ezraroi/ngJsTree#96]
I am using https://github.com/ezraroi/ngJsTree and I have come across the following problem.

My ng-model is a AJAX request and when my controller fires, data is not yet ready, so it does not render anything.

```
<div ng-controller='myCtrl'>
    <div js-tree="treeConfig" ng-model="treeData" should-apply="ignoreModelChanges()" tree="treeInstance" tree-events="ready:readyCB;create_node:createNodeCB"></div>
</div>
```

http://plnkr.co/edit/IRaqvd0DPcqkxgo0xoqa?p=preview

**Comment by ezraroi** [comment]
Where is your treeConfig? looks like you didn't define such one... this is your problem
